services:
  api:
    image: php:8.2-fpm
    ports:
      - "8090:9000"  # Cambiamos a 8090 para evitar conflictos
    volumes:
      - .:/var/www
    environment:
      - APP_ENV=production
      - DB_HOST=dpg-d1q7lrer433s73e2s0ng-a.oregon-postgres.render.com
      - DB_PORT=5432
      - DB_DATABASE=boletoscore_db
      - DB_USERNAME=boletoscore_db_user
      - DB_PASSWORD=MIyGBIrWGfAwuutFnUT8DbDS7WfWgN3c
      - DB_SSLMODE=require
    command: >
      sh -c "docker-php-ext-install pdo pdo_pgsql &&
             composer install --no-scripts --no-interaction &&
             php-fpm"
  kong:
    image: kong:3.0  # Versión específica para evitar descargar 'latest'
    environment:
      - KONG_DATABASE=off
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_PROXY_LISTEN=0.0.0.0:8081
      - KONG_LOG_LEVEL=info
    ports:
      - "8081:8081"
      - "8001:8001"
    depends_on:
      - api